import type { Metadata } from "next";
import { SpeedInsights } from "@vercel/speed-insights/next"
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Kirundi Translator",
  description: "Generated by AU",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SpeedInsights/>
      <link rel="shortcut icon" href={"/assets/burundi.png"} />
      <body className="font-primary">{children}</body>
      <Script strategy="afterInteractive" src="https://www.googletagmanager.com/gtag/js?id=G-2BLSYNY1YR"/>
      <Script id="google-analytics" strategy="afterInteractive">
          {`window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());

          gtag('config', 'G-2BLSYNY1YR');`}
      </Script>
    </html>
  );
}
